Delivr/Delivr/Controllers/MenuController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using Delivr.Models;
using WebMatrix.WebData;

namespace Delivr.Controllers
{
    public class MenuController : Controller
    {
        private DelivrContext db = new DelivrContext();

        //
        // GET: /Menu/Details/5

        public ActionResult Details(int id = 0)
        {
            Menu menu = db.Menus.Find(id);
            if (menu == null)
            {
                return HttpNotFound();
            }
            return View(menu);
        }
        
        //
        // GET: /Menu/BlankMenuItemRow

        public ActionResult BlankMenuItemRow()
        {
            return PartialView("MenuItemRow", new EditMenuItemModel());
        }

        //
        // GET: /Menu/EditForRestaurant/5

        public ActionResult EditForRestaurant(int? restaurantId = null)
        {
            if (restaurantId == null)
                return HttpNotFound();

            Restaurant restaurant = db.Restaurants.Find(restaurantId);
            if (restaurant == null || (!User.IsInRole("Admin") && restaurant.UserId != WebSecurity.CurrentUserId))
                return HttpNotFound();

            ViewBag.ShowWarnings = true;
            return View(restaurant);
        }

        //
        // POST: /Menu/Edit

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit(EditMenuModel model)
        {
            // Simple security to avoid trying to edit an non-existing menu
            if (!model.MenuId.HasValue)
                return HttpNotFound();

            if (ModelState.IsValid)
            {
                // Generate a list of MenuItems used by this Menu
                List<MenuItem> menuItems = new List<MenuItem>();
                if (model.MenuItemModels != null)
                {
                    foreach (EditMenuItemModel itemModel in model.MenuItemModels)
                    {
                        MenuItem item;
                        if (itemModel.MenuItemId.HasValue)
                        {
                            item = db.MenuItems.Find(itemModel.MenuItemId.Value);
                            item.Nom = itemModel.Nom;
                            item.Description = itemModel.Description;
                            item.Prix = Decimal.ToInt32(itemModel.Prix * 100);

                            // Indicate the item was modified:
                            db.Entry(item).State = EntityState.Modified;
                        }
                        else
                        {
                            item = new MenuItem()
                            {
                                Nom = itemModel.Nom,
                                Description = itemModel.Description,
                                Prix = Decimal.ToInt32(itemModel.Prix * 100)
                            };

                            db.MenuItems.Add(item);
                        }

                        menuItems.Add(item);
                    }
                }

                Menu menu = db.Menus.Find(model.MenuId.Value);

                // Iterate through the items of the stored menu:
                foreach (MenuItem item in menu.MenuItems.ToList())
                {
                    // If the item does not exist in the presentation model, it has been removed.
                    // Remove from database if there was no CommandeItem associated to the Item.
                    if (!item.CommandeItems.Any() && !model.MenuItemModels.Any(itemModel =>
                        itemModel.MenuItemId.HasValue && itemModel.MenuItemId.Value == item.MenuItemId))
                    {
                        db.MenuItems.Remove(item);
                    }
                }

                menu.Nom = model.Nom;
                menu.MenuItems = menuItems;

                // Indicate the menu was modified:
                db.Entry(menu).State = EntityState.Modified;
                db.SaveChanges();

                model = new EditMenuModel(menu); // Update the presentation model with exact data
                ViewBag.SuccessMessage = Resources.Menu.MenuDefinitionSuccessMessage;
                ModelState.Clear();
            }

            ViewBag.ShowWarnings = true;
            return PartialView("AddEditMenuPartial", model);
        }

        //
        // POST: /Menu/Add

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Add(EditMenuModel model)
        {
            if (ModelState.IsValid)
            {
                // Generate a list of MenuItems used by this Menu
                List<MenuItem> menuItems = new List<MenuItem>();
                if (model.MenuItemModels != null)
                {
                    foreach (EditMenuItemModel itemModel in model.MenuItemModels)
                    {
                        MenuItem item = new MenuItem()
                        {
                            Nom = itemModel.Nom,
                            Description = itemModel.Description,
                            Prix = Decimal.ToInt32(itemModel.Prix * 100)
                        };

                        db.MenuItems.Add(item);
                        menuItems.Add(item);
                    }
                }

                // Create a new Menu with the information provided, and the MenuItems generated
                Menu menu = new Menu()
                {
                    Nom = model.Nom,
                    RestaurantId = model.RestaurantId,
                    MenuItems = menuItems
                };

                db.Menus.Add(menu);
                db.SaveChanges();

                model = new EditMenuModel(menu); // Update the presentation model with exact data
                ViewBag.SuccessMessage = Resources.Menu.MenuDefinitionSuccessMessage;
                ModelState.Clear();
            }

            ViewBag.ShowWarnings = true;
            return PartialView("AddEditMenuPartial", model);
        }

        protected override void Dispose(bool disposing)
        {
            db.Dispose();
            base.Dispose(disposing);
        }
    }
}

Delivr/Delivr/Controllers/RestaurantController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using Delivr.Models;
using WebMatrix.WebData;
using System.Web.Security;
using System.Net.Mail;
using System.Net;
using System.Text;
using System.IO;
using Delivr.Helpers;

namespace Delivr.Controllers
{
    public class RestaurantController : Controller
    {
        private DelivrContext db = new DelivrContext();
        private TwilioHelper twilio = new TwilioHelper();

        //
        // GET: /Restaurant/

        public ActionResult Index()
        {
            return View(db.Restaurants.ToList());
        }


        //
        // GET: /Restaurant/MenuNotFound
        public ActionResult MenuNotFound()
        {
            return View();
        }

        //
        // GET: /Restaurant/

        public ActionResult MenuCommande(int id)
        {
            Restaurant resto = db.Restaurants.Find(id);
            List<Menu> menus = new List<Menu>();
            List<MenuItem> menuItems = new List<MenuItem>();
            List<CreateCommandeItemModel> createCommandeItems = new List<CreateCommandeItemModel>();

            if (db.Menus.Where(c => c.RestaurantId == resto.RestaurantId).FirstOrDefault() == null)
            {
                return RedirectToAction("MenuNotFound");
            }
            foreach (Menu m in db.Menus.Where(c => c.RestaurantId == resto.RestaurantId).ToList())
            {
                foreach (MenuItem mi in db.MenuItems.Where(c => c.MenuId == m.MenuId).ToList())
                {
                    CreateCommandeItemModel model = new CreateCommandeItemModel(0, mi.MenuItemId, mi.Nom, mi.Prix, id);
                    createCommandeItems.Add(model);
                }
            }

            return View(createCommandeItems);
        }

        [HttpPost]
        public ActionResult MenuCommande(IList<Delivr.Models.CreateCommandeItemModel> createCommandeItems)
        {


            List<CommandeItem> items = new List<CommandeItem>();
            foreach (CreateCommandeItemModel c in createCommandeItems)
            {
                if (c.Quantite != 0)
                {
                    CommandeItem cItem = new CommandeItem()
                    {
                        MenuItemId = c.MenuItemId,
                        Quantite = c.Quantite,
                        SousTotal = c.Quantite * c.Prix

                    };

                    items.Add(cItem);
                }
            }
            TempData["list"] = items;
            return RedirectToAction("CreateCommande");
        }



        //
        // GET: /Restaurant/CreateCommande

        public ActionResult CreateCommande()
        {

            var items = TempData["list"] as List<CommandeItem>;
            if (items == null)
                return RedirectToAction("Liste");
            CreateCommandeModel createCommande = new CreateCommandeModel();
            MenuItem firstMenuItem = db.MenuItems.Find(items.First().MenuItemId);
            Menu menu = db.Menus.Find(firstMenuItem.MenuId);
            Restaurant resto = db.Restaurants.Find(menu.RestaurantId);
            UserProfile user = db.UserProfiles.Find(WebSecurity.CurrentUserId);
            List<MenuItem> menuItems = db.MenuItems.Where(c => c.MenuId == menu.MenuId).ToList();
            List<CommandeItem> commandeItems = new List<CommandeItem>();
            foreach (CommandeItem ci in items)
            {
                firstMenuItem = db.MenuItems.Find(ci.MenuItemId);
                ci.MenuItem = firstMenuItem;
                createCommande.CommandeItems.Add(ci);
            }

            foreach (Adresse ad in user.Adresses)
            {
                if (user.AdresseDefaultId != ad.AdresseId)
                    createCommande.Adresses.Add(ad);
                else
                    createCommande.AdresseDefault = ad;
            }

            createCommande.Date = DateTime.Now;
            return View(createCommande);
        }

        //
        // GET: /Restaurant/CreateCommande

        [HttpPost]
        public ActionResult CreateCommande(CreateCommandeModel createCommande)
        {
            Commande commande;

            UserProfile user = db.UserProfiles.Find(WebSecurity.CurrentUserId);
            MenuItem firstMenuItem = db.MenuItems.Find(createCommande.CommandeItems.First().MenuItemId);
            Menu menu = db.Menus.Find(firstMenuItem.MenuId);
            Restaurant resto = db.Restaurants.Find(menu.RestaurantId);

            int AdresseId = createCommande.AdresseId;
            if ((createCommande.NewAdresse.Rue == null || createCommande.NewAdresse.Rue == ""))
            {
                AdresseId = createCommande.AdresseId;
                user.AdresseDefaultId = AdresseId;
            }
            else
            {
                Adresse add = new Adresse();
                add.NumeroCivique = createCommande.NewAdresse.NumeroCivique;
                add.CodePostale = createCommande.NewAdresse.CodePostale;
                add.Rue = createCommande.NewAdresse.Rue;
                add.User = user;
                db.Adresses.Add(add);
                db.SaveChanges();
                user.Adresses.Add(add);
                AdresseId = add.AdresseId;
                user.AdresseDefaultId = add.AdresseId;
            }


            commande = new Commande()
            {
                AdresseId = AdresseId,
                RestaurantId = resto.RestaurantId,
                UserId = user.UserId,
                Date = createCommande.Date,
                Statut = Commande.StatutCommande.EnTraitement, //sera mis a jour sur réception du paiement
                PaypalTransacId = null //sera inséré par la suite
            };

            commande.Adresse = db.Adresses.Find(AdresseId);
            foreach (CommandeItem c in createCommande.CommandeItems)
            {
                db.CommandeItems.Add(c);
            }

            commande.CommandeItems = createCommande.CommandeItems;
            commande.Adresse = db.Adresses.Find(AdresseId);
            db.Commandes.Add(commande);
            db.SaveChanges();


            string items = Environment.NewLine + "Items: ";
            string totalString = "Total: ";
            int total = 0;
            foreach (CommandeItem c in commande.CommandeItems)
            {
                MenuItem mi = db.MenuItems.Find(c.MenuItemId);
                items += mi.Nom + " x" + c.Quantite.ToString() + "" + Environment.NewLine;
                total = total + c.SousTotal;
            }
            totalString += total.ToString();
            twilio.SendSMS("Vous avez placé une nouvelle commande! Numéro de confirmation: " + commande.CommandeId + " État: " + commande.Statut, user.Telephone);
            SendMail("Confirmation de commande Delivr (Processing)", 
                        "Numéro de confirmation: " + commande.CommandeId + Environment.NewLine + "Adresse: " + commande.Adresse.NumeroCivique + " " + 
                        commande.Adresse.Rue + " " + commande.Adresse.CodePostale + Environment.NewLine + "Date et heure:" + 
                        commande.Date.ToString("MM/dd/yyyy HH:mm:ss.fff") + " " + items + totalString, user.UserName);

            return Content(commande.CommandeId.ToString());

            //-----------------------------------------------------------------------------------------
        }

        //
        // GET: /Restaurant/ConfirmationCommande

        public ActionResult ConfirmationCommande()
        {
            // Receive IPN request from PayPal and parse all the variables returned
            var formVals = new Dictionary<string, string>();
            formVals.Add("cmd", "_notify-synch");
            formVals.Add("at", "ZjUQz8PtolJAdGtMs2OnKyzlPXJa0-oFywH2fbntTO2SXpVFKFrUl2sRuJC"); //identity-token
            formVals.Add("tx", Request["tx"].ToUpper());

            //true for sandbox
            string response = GetPayPalResponse(formVals, true);
            string[] args = response.Split(new string[] { "\n" }, StringSplitOptions.None);
            string orderId = args.First(x => x.Contains("custom")).Split('=')[1];
               
            Commande order = db.Commandes.Find(Int32.Parse(orderId));

            if (response.Contains("SUCCESS"))
            {
                string transactionID = GetPDTValue(response, "txn_id"); // txn_id //d
                string sAmountPaid = GetPDTValue(response, "mc_gross"); // d
                string deviceID = GetPDTValue(response, "custom"); // d
                string payerEmail = GetPDTValue(response, "payer_email"); // d
                string Item = GetPDTValue(response, "item_name");

                Decimal amountPaid = 0;
                Decimal.TryParse(sAmountPaid, System.Globalization.NumberStyles.Number, System.Globalization.CultureInfo.InvariantCulture, out amountPaid);

                if (amountPaid == (decimal)order.Prix/100)  // you might want to have a bigger than or equal to sign here!
                {
                    ViewBag.Result = "SUCCESS";
                    order.PaypalTransacId = transactionID;
                    order.Statut = Commande.StatutCommande.EnAttente;
                    TryUpdateModel(order);
                    db.SaveChanges();
                    UserProfile user = db.UserProfiles.Find(order.UserId);
                    twilio.SendSMS("Votre commande #: " + order.CommandeId + " est maintenant: " + order.Statut, user.Telephone);
                }
                else
                {
                    ViewBag.Result = "WRONG_AMOUNT";
                }

            }
            else
            {
                //Payment failure
                ViewBag.Result = "PAYMENT_FAILURE";
            }

            return View(order);
        }

        //------------------------PAYPAL UTILS----------------------------------------------

Delivr/Delivr/Views/Menu/AddEditMenuPartial.cshtml
@using Resources = Delivr.Resources;
@model Delivr.Models.EditMenuModel
@{
    bool editMode = Model.MenuId.HasValue;

    using (Html.BeginForm(editMode ? "Edit" : "Add", "Menu", FormMethod.Post,
        new { @class = (editMode ? "edit-menu-form" : "add-menu-form") + (ViewData.ModelState.IsValid ? "" : " in-error") }))
    {
        @Html.AntiForgeryToken()
        if (ViewBag.SuccessMessage != null)
        {
            <div class="alert alert-in-tab alert-success" role="alert">
                <button type="button" class="close" data-dismiss="alert" aria-label="Close">
                    <span aria-hidden="true">&times;</span>
                </button>
                @ViewBag.SuccessMessage
            </div>
        }
        @Html.ValidationSummary(true)

        @Html.HiddenFor(model => model.MenuId)
        @Html.HiddenFor(model => model.RestaurantId)

        if (ViewData.ModelState.IsValidField("Nom"))
        {
            <div class="form-group">
                @Html.LabelFor(model => model.Nom, new { @class = "control-label" })
                @Html.TextBoxFor(model => model.Nom, new { @class = "form-control" })
            </div>
        }
        else
        {
            <div class="form-group has-error">
                @Html.LabelFor(model => model.Nom, new { @class = "control-label" })
                @Html.ValidationMessageFor(model => model.Nom, "", new { @class = "text-danger bg-danger", style = "margin-left: 10px" })
                @Html.TextBoxFor(model => model.Nom, new { @class = "form-control" })
            </div>
        }

        <div class="form-group">
            @Html.LabelFor(model => model.MenuItemModels, new { @class = "control-label", style = "width: 100%; border-bottom: solid 1px" })
            <div class="menu-items-list">
                @if (Model.MenuItemModels != null)
                {
                    foreach (var itemModel in Model.MenuItemModels)
                    {
                        Html.RenderPartial("MenuItemRow", itemModel);
                    }
                }
            </div>
        </div>

        <div class="form-group">
            <div class="col-sm-10 control-label">
                @Html.ActionLink(Resources.Menu.AddItem, "BlankMenuItemRow", null, new { @class = "btn btn-default bnt-small add-item" })
                <input type="submit" class="btn btn-primary" value="@Resources.General.Save" />
            </div>
        </div>
    }
}

Delivr/Delivr/Views/Menu/EditForRestaurant.cshtml
@using Resources = Delivr.Resources;
@model Delivr.Models.Restaurant
@{
    ViewBag.Title = @Resources.Menu.PageTitle;
}


<div class="jumbotron padded">
    <div class="container">
        <h2>@ViewBag.Title : @Model.nom</h2>

        <ul id="menu-tabs" class="nav nav-tabs">
            @{
                System.Text.StringBuilder tabContentBuilder = new System.Text.StringBuilder("<div id=\"menu-tabs-content\" class=\"tab-content\">\n");
                bool first = true;
                foreach (var menu in Model.Menus)
                {
                    string additionalClasses = "";
                    if (first)
                    {
                        additionalClasses = "active";
                        first = false;
                    }

                    <li role="presentation" class="@additionalClasses">
                        <a id="tab_@(menu.MenuId)" href="#tabpanel_@(menu.MenuId)" role="tab" data-toggle="tab">@menu.Nom</a>
                    </li>

                    tabContentBuilder.AppendFormat("<div role=\"tabpanel\" class=\"tab-pane menu {0}\" id=\"tabpanel_{1}\" data-tab=\"tab_{1}\">\n", additionalClasses, menu.MenuId);
                    tabContentBuilder.Append(Html.Partial("AddEditMenuPartial", new Delivr.Models.EditMenuModel(menu)));
                    tabContentBuilder.AppendLine("</div>");
                }

                <li role="presentation" class="@(first ? "active" : "")">
                    <a id="tab_new" href="#tabpanel_new" role="tab" data-toggle="tab">+</a>
                </li>

                tabContentBuilder.AppendFormat("<div role=\"tabpanel\" class=\"tab-pane menu {0}\" id=\"tabpanel_new\">", first ? "active" : "");
                tabContentBuilder.Append(Html.Partial("AddEditMenuPartial", new Delivr.Models.EditMenuModel() { RestaurantId = Model.RestaurantId }));
                tabContentBuilder.AppendLine("</div>");

                tabContentBuilder.AppendLine("</div>");
            }
        </ul>

        @* Render the tabs content *@
        @Html.Raw(tabContentBuilder.ToString())
    </div>
    <div class="container">
        <hr />
        <div class="btn-group btn-group-sm" role="group" aria-label="controls">
            @if (User.IsInRole("Admin"))
            {
                @Html.ActionLink(Resources.General.BackToListing, "Index", "Restaurant", null, new { @class = "btn btn-default" })
                @Html.ActionLink(Resources.General.BackToDetails, "Details", "Restaurant", new { id = Model.RestaurantId }, new { @class = "btn btn-default" })
            }
            else if (User.IsInRole("Restaurateur"))
            {
                @Html.ActionLink(Resources.Menu.BackToRestaurants, "IndexForRestaurateur", "Restaurant", new { id = WebSecurity.CurrentUserId }, null)
            }
        </div>
    </div>
</div>

@section Scripts {
    <script>
        // Tabs level event handlers:
        $("#menu-tabs-content").on("submit", ".edit-menu-form", function () {

            $menu = $(this).parent();
            $(this).ajaxSubmit(function (html) {

                $menu.html(html);
                // If not in error:
                if (!$(".edit-menu-form", $menu).hasClass("in-error")) {
                    $("#" + $menu.attr("data-tab")).html($("input[name=Nom]", $menu).val());
                }
            });

            return false;
        });

        $("#menu-tabs-content").on("submit", ".add-menu-form", function () {

            $(this).ajaxSubmit(function (html) {

                // If not in error:
                if (!($(html).hasClass("in-error"))) {

                    var id = $("input[name=MenuId]", html).val();
                    var nom = $("input[name=Nom]", html).val();

                    $("#tab_new").parent().before(
                          "<li role='presentation'>"
                        + "    <a id='tab_" + id + "' href='#tabpanel_" + id + "' role='tab' data-toggle='tab'>" + nom + "</a>"
                        + "</li>");

                    $("#tabpanel_new").before(
                          "<div role='tabpanel' class='tab-pane menu' id='tabpanel_" + id + "' data-tab='tab_" + id + "'>"
                        + html
                        + "</div>");

                    $("#tabpanel_new").html(
                        @Html.Raw(HttpUtility.JavaScriptStringEncode(
                            Html.Partial("AddEditMenuPartial", new Delivr.Models.EditMenuModel() { RestaurantId = Model.RestaurantId }).ToString(),
                            true)));

                    $("#tab_" + id).tab("show");

                } else {

                    $("#tabpanel_new").html(html);

                }
            });

            return false;
        });

        // Menu level event handlers:
        $("#menu-tabs-content").on("click", ".add-item", function () {
            $menu = $(this).parents(".menu");
            $.ajax({
                url: this.href,
                cache: false,
                success: function (html) { $(".menu-items-list", $menu).append(html); }
            });
            return false;
        });

        $("#menu-tabs-content").on("click", ".menu-items-list .removeItem", function () {
            $(this).parents("div.editor-row:first").remove();
            return false;
        });
    </script>
}

Delivr/Delivr/Views/Menu/EditMenuPartial.cshtml
@model Delivr.Models.EditMenuModel
@{
    bool editMode = Model.MenuId.HasValue;

    using (Html.BeginForm(editMode ? "Edit" : "Add", "Menu", FormMethod.Post,
        new { @class = (editMode ? "edit-menu-form" : "add-menu-form") + (ViewData.ModelState.IsValid ? "" : " in-error") }))
    {
        @Html.AntiForgeryToken()
        if (ViewBag.SuccessMessage != null)
        {
            <div class="alert alert-success" role="alert">
                <button type="button" class="close" data-dismiss="alert" aria-label="Close">
                    <span aria-hidden="true">&times;</span>
                </button>
                @ViewBag.SuccessMessage
            </div>
        }
        @Html.ValidationSummary(true)

        @Html.HiddenFor(model => model.MenuId)

        if (ViewData.ModelState.IsValidField("Nom"))
        {
            <div class="form-group">
                @Html.LabelFor(model => model.Nom, new { @class = "control-label" })
                @Html.TextBoxFor(model => model.Nom, new { @class = "form-control" })
            </div>
        }
        else
        {
            <div class="form-group has-error">
                @Html.LabelFor(model => model.Nom, new { @class = "control-label" })
                @Html.ValidationMessageFor(model => model.Nom, "", new { @class = "text-danger bg-danger", style = "margin-left: 10px" })
                @Html.TextBoxFor(model => model.Nom, new { @class = "form-control" })
            </div>
        }

        <div class="form-group">
            @Html.LabelFor(model => model.MenuItemModels, new { @class = "control-label", style = "width: 100%; border-bottom: solid 1px" })
            <div class="menu-items-list">
                @if (Model.MenuItemModels != null)
                {
                    foreach (var itemModel in Model.MenuItemModels)
                    {
                        Html.RenderPartial("MenuItemRow", itemModel);
                    }
                }
            </div>
        </div>

        <div class="form-group">
            <div class="col-sm-10 control-label">
                @Html.ActionLink(Resources.Menu.AddItem, "BlankMenuItemRow", null, new { @class = "btn btn-default bnt-small add-item" })
                <input type="submit" class="btn btn-primary" value="@Resources.General.Save" />
            </div>
        </div>
    }
}

Delivr/Delivr/Views/Menu/MenuItemRow.cshtml
@using Delivr.Helpers
@using Resources = Delivr.Resources;
@model Delivr.Models.EditMenuItemModel

<div class="editor-row form-inline">
    @using (Html.BeginCollectionItem("MenuItemModels"))
    {
        @Html.HiddenFor(model => model.MenuItemId)
        <div class="form-group form-group-sm">
            @Html.LabelFor(model => model.Nom, new { @class = "control-label small" })
            @Html.TextBoxFor(model => model.Nom, new { @class = "form-control" })
        </div>
        <div class="form-group form-group-sm">
            @Html.LabelFor(model => model.Description, new { @class = "control-label small" })
            @Html.TextAreaFor(model => model.Description, new { @class = "form-control" })
        </div>
        <div class="form-group form-group-sm">
            @Html.LabelFor(model => model.Prix, new { @class = "control-label small" })
            @Html.TextBoxFor(model => model.Prix, new { @class = "form-control" })
        </div>
        <div class="form-group">
            <button class="btn btn-default btn-sm removeItem">@Resources.Menu.RemoveItem</button>
        </div>

        @* Check for errors *@
        if (ViewData.ModelState.Keys.Any(s => s.StartsWith(ViewData.TemplateInfo.HtmlFieldPrefix) && !ViewData.ModelState.IsValidField(s)))
        {
            <div class="form-group">
                <div class="alert alert-sm alert-danger">
                    @Html.ValidationMessageFor(model => model.Nom)
                    @Html.ValidationMessageFor(model => model.Description)
                    @Html.ValidationMessageFor(model => model.Prix)
                </div>
            </div>
        }

        @* Check for missing description *@
        if ((ViewBag.ShowWarnings ?? false) && String.IsNullOrWhiteSpace(Model.Description))
        {
            <div class="form-group">
                <div class="alert alert-sm alert-warning">
                    @Resources.Menu.DescriptionMissingWarning
                </div>
            </div>
        }
    }
</div>